-- ============================================================
-- ゲームキャラクター管理データベース スキーマ定義
-- ============================================================
-- このスクリプトは、ゲームのキャラクター、ギルド、アイテム、
-- ゴールド送金履歴を管理するためのテーブル群を作成します。
-- ============================================================
-- UUID生成のための拡張機能を有効化
-- pgcrypto: PostgreSQLの暗号化関数拡張機能
--   この拡張により、GEN_RANDOM_UUID()関数などが使用可能になります。
--   UUID（Universally Unique Identifier）は、一意性が保証された128ビットの識別子で、
--   分散システムでも重複の心配なく使用できます。
--   IF NOT EXISTS: 既に拡張が存在する場合はエラーを発生させずスキップします。
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- トランザクションの開始
-- トランザクション: 複数のSQL文をひとまとまりの処理単位として扱う仕組み。
--   全ての処理が成功した場合のみ変更が確定（COMMIT）され、
--   途中でエラーが発生した場合は全ての変更が取り消される（ROLLBACK）。
--   これによりデータの整合性を保つことができます。
START TRANSACTION;

-- ============================================================
-- 既存テーブルの削除（外部キー制約を考慮した順序で削除）
-- ============================================================
-- DROP TABLE IF EXISTS: 指定したテーブルが存在する場合のみ削除します。
--   存在しない場合はエラーにならずスキップされるため、初回実行でも安全です。
--   外部キー制約で参照されているテーブルは、参照する側を先に削除する必要があります。
-- ============================================================
DROP TABLE IF EXISTS x_gold_transfers;

DROP TABLE IF EXISTS x_character_items;

DROP TABLE IF EXISTS x_guild_characters;

DROP TABLE IF EXISTS x_guilds;

DROP TABLE IF EXISTS x_characters;

DROP TABLE IF EXISTS x_jobs;

DROP TABLE IF EXISTS x_items;

-- ============================================================
-- アイテムのマスタテーブル
-- ============================================================
-- ゲーム内で使用される全アイテムの定義を管理します。
-- 価格、重量、説明などの基本情報を保持します。
-- ============================================================
CREATE TABLE x_items (
    -- GENERATED BY DEFAULT AS IDENTITY: 連番を自動生成する列定義
    --   新しい行が挿入される際に、自動的に1, 2, 3...と連番が割り当てられます。
    --   BY DEFAULT: 明示的に値を指定することも可能（BY ALWAYSの場合は不可）
    -- PRIMARY KEY（主キー）: テーブル内の各行を一意に識別するための列
    --   NULL不可、重複不可、テーブルに1つだけ定義可能
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- UNIQUE制約: この列の値が他の行と重複しないことを保証
    --   PRIMARY KEYとは異なり、複数の列にUNIQUE制約を設定可能
    name VARCHAR(32) NOT NULL UNIQUE,
    -- CHECK制約: 列に格納できる値の条件を定義
    --   この例では、価格が0以上であることを強制します
    --   条件に違反する値を挿入しようとするとエラーになります
    price INTEGER NOT NULL CHECK (price >= 0),
    -- DECIMAL(4, 1): 精度を持つ数値型
    --   全体で4桁、小数点以下1桁の数値を格納（例: 999.9まで）
    weight_kg DECIMAL(4, 1) NOT NULL,
    -- TEXT: 可変長の文字列型（長さ制限なし）
    description TEXT
);

-- ============================================================
-- ジョブ（職業）のマスタテーブル
-- ============================================================
-- キャラクターが選択できる職業の定義を管理します。
-- 各職業は固有の攻撃力、防御力、魔力の成長率を持ちます。
-- ============================================================
CREATE TABLE x_jobs (
    job_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ジョブID（自動採番）
    name VARCHAR(16) NOT NULL UNIQUE, -- ジョブ名（重複不可）
    attack_gain INTEGER NOT NULL, -- レベルアップ時の攻撃力上昇値
    defense_gain INTEGER NOT NULL, -- レベルアップ時の防御力上昇値
    magic_gain INTEGER NOT NULL -- レベルアップ時の魔力上昇値
);

-- ============================================================
-- キャラクタのマスタテーブル
-- ============================================================
-- ゲーム内のキャラクターの基本情報を管理します。
-- 【論理削除】について:
--   物理削除: データを実際にDBから削除する方式
--   論理削除: 削除フラグや削除日時を設定し、見かけ上削除されたように扱う方式
--   論理削除のメリット:
--     - 削除されたデータの履歴を保持できる
--     - 誤削除時の復旧が容易
--     - 監査ログとして利用可能
-- ============================================================
CREATE TABLE x_characters (
    character_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(16) NOT NULL,
    -- BETWEEN: 範囲指定のCHECK制約（境界値を含む）
    --   level >= 1 AND level <= 255 と同じ意味
    level INTEGER NOT NULL CHECK (level BETWEEN 1 AND 255),
    -- REFERENCES: 外部キー制約（参照整合性制約）
    --   他のテーブルの主キーを参照し、データの整合性を保証します。
    --   この例では、job_idはx_jobsテーブルに存在するjob_idのみ設定可能です。
    --   存在しないjob_idを指定しようとするとエラーになります。
    job_id INTEGER NOT NULL REFERENCES x_jobs (job_id),
    -- DEFAULT LOCALTIMESTAMP(0): デフォルト値の設定
    --   LOCALTIMESTAMP: 現在のローカル日時を返す関数
    --   (0): 秒単位で切り捨て（ミリ秒以下を含まない）
    --   値を指定しない場合、自動的に現在日時が設定されます
    created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP(0),
    -- 論理削除用のフラグカラム
    --   NULL: 削除されていない（アクティブな状態）
    --   日時が入っている: その日時に削除された
    deleted_at TIMESTAMP,
    -- 削除日時は作成日時以降である必要がある
    CHECK (
        deleted_at IS NULL OR
        deleted_at >= created_at
    )
);

-- ============================================================
-- ギルドのマスタテーブル
-- ============================================================
-- プレイヤーが作成するギルド（組合・ギルド）の情報を管理します。
-- 各ギルドには1人のオーナー（ギルドマスター）が必ず存在します。
-- オーナーキャラクターが削除されるとギルドも削除されます。
-- ============================================================
CREATE TABLE x_guilds (
    guild_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(16) NOT NULL UNIQUE,
    -- ON DELETE CASCADE: カスケード削除
    --   参照先のレコード（この場合はキャラクター）が削除されたとき、
    --   このレコード（ギルド）も自動的に削除されます。
    --   他のオプション:
    --     ON DELETE RESTRICT: 参照されている間は削除を禁止（デフォルト）
    --     ON DELETE SET NULL: 参照先が削除されたらNULLに設定
    --     ON DELETE SET DEFAULT: 参照先が削除されたらデフォルト値に設定
    owner_id INTEGER NOT NULL REFERENCES x_characters (character_id) ON DELETE CASCADE
);

-- ============================================================
-- ギルドとキャラクタの所属関係を表す中間テーブル
-- ============================================================
-- 【多対多の関係】について:
--   1人のキャラクターが複数のギルドに所属でき、
--   1つのギルドに複数のキャラクターが所属できる関係。
--   この関係を実現するために中間テーブル（連関テーブル）を使用します。
-- ギルドまたはキャラクターが削除されると、対応する所属情報も削除されます。
-- ============================================================
CREATE TABLE x_guild_characters (
    guild_id INTEGER REFERENCES x_guilds (guild_id) ON DELETE CASCADE,
    character_id INTEGER REFERENCES x_characters (character_id) ON DELETE CASCADE,
    -- 複合主キー: 複数の列を組み合わせて主キーとする
    --   この例では、「同じキャラクターが同じギルドに重複して所属できない」
    --   ことを保証します。
    --   (character_id=1, guild_id=1) という組み合わせは1つしか存在できません。
    PRIMARY KEY (character_id, guild_id)
);

-- ============================================================
-- キャラクタが所持するアイテムと数量を管理する中間テーブル
-- ============================================================
-- キャラクターとアイテムの多対多の関係を管理します。
-- 各キャラクターがどのアイテムを何個持っているかを記録します。
-- キャラクターが削除されると、所持アイテム情報も削除されます。
-- ============================================================
CREATE TABLE x_character_items (
    character_id INTEGER REFERENCES x_characters (character_id) ON DELETE CASCADE, -- キャラクターID（外部キー）
    item_id INTEGER REFERENCES x_items (item_id), -- アイテムID（外部キー）
    qty INTEGER NOT NULL CHECK (qty >= 0), -- 所持数量（0以上）
    PRIMARY KEY (character_id, item_id) -- 複合主キー
);

-- ============================================================
-- キャラクタ同士、またはシステムとのゴールド送受信履歴を記録するトランザクションテーブル
-- ============================================================
-- ゲーム内通貨（ゴールド）の送金履歴を記録します。
-- 送信元・送信先のいずれかがNULLの場合、その相手は「システム」を表します。
-- （例：クエスト報酬の受け取り、アイテム購入など）
-- ============================================================
CREATE TABLE x_gold_transfers (
    -- UUID: 汎用一意識別子（128ビット、16進数で表記）
    --   例: 550e8400-e29b-41d4-a716-446655440000
    --   通常のINTEGERと比較したUUIDの利点:
    --     - 分散システムでも衝突（重複）の可能性が極めて低い
    --     - 連番でないため、ID値から登録順序や件数を推測されにくい（セキュリティ向上）
    -- GEN_RANDOM_UUID(): ランダムなUUIDを生成する関数（pgcrypto拡張が必要）
    transfer_id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    from_character_id INTEGER REFERENCES x_characters (character_id), -- 送信元キャラクターID（NULL=システム）
    to_character_id INTEGER REFERENCES x_characters (character_id), -- 送信先キャラクターID（NULL=システム）
    amount INTEGER NOT NULL CHECK (amount > 0), -- 送金額（1以上）
    transferred_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP(0), -- 送金日時（秒単位）
    -- 送信元と送信先の少なくとも一方は存在する必要がある
    CHECK (
        from_character_id IS NOT NULL OR
        to_character_id IS NOT NULL
    ),
    -- 自分自身への送金は禁止
    CHECK (
        from_character_id IS NULL OR
        to_character_id IS NULL OR
        from_character_id <> to_character_id
    )
);

-- トランザクションのコミット（確定）
-- COMMIT: トランザクション内で実行された全ての変更を確定します。
--   START TRANSACTIONからCOMMITまでの全処理が成功した場合のみ、
--   データベースに変更が反映されます。
--   途中でエラーが発生した場合は自動的にROLLBACKされ、
--   全ての変更が取り消されます。
COMMIT;